### ISSUE TITLE
新建路由

### ISSUE THREAD

**Issue by Hxmic** [tearill/Reading_Record#2]
新建路由，小程序中并没有生效。你有没有demo。

**Comment by tearill** [comment]
有的哦，这是我在掘金发的文章的文件，readme 中已经把详细的配置写出来了，你可以看看~


------------------ 原始邮件 ------------------
发件人:&nbsp;"Hxmic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上9:45
收件人:&nbsp;"tearill/Reading_Record"<Reading_Record@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tearill/Reading_Record] 新建路由 (#2)





 
新建路由，小程序中并没有生效。你有没有demo。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

multipages.rar (45.18M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=73393632e93b1e9b12f6d77343340149510f04505c5652001d5f525104190704060d1b0a52020b4b560d55045c07500052010007653a330b4555425b155554034317445317340e&t=exs_ftn_download&code=0962e43f
